import React, { useState, useEffect, useCallback } from "react";
import { Card, Typography, Tag, Button, Space, Tree, Input, Modal, Form, Select, App, Row, Col, List, Divider, Tabs, Spin, Empty, Statistic, Badge, Descriptions, Tooltip, message as antMessage, Alert, Popconfirm } from "antd";
import {
  PlusOutlined, DatabaseOutlined, FileTextOutlined, RobotOutlined,
  FolderOpenOutlined, CheckCircleOutlined, ClockCircleOutlined,
  ThunderboltOutlined, BookOutlined, ReloadOutlined, BarChartOutlined,
  TeamOutlined, CalendarOutlined, FileSearchOutlined, EditOutlined,
  DeleteOutlined, EyeOutlined,
} from "@ant-design/icons";
import { projectDocsApi, projectApi } from "../api";

const { Title, Text, Paragraph } = Typography;
const { TextArea } = Input;

// PMBOK 过程组图标与颜色
const GROUP_ICONS: Record<string, string> = {
  initiating: "🚀", planning: "📋", executing: "⚡", monitoring: "🔍", closing: "🎯",
};
const GROUP_COLORS: Record<string, string> = {
  initiating: "#6366F1", planning: "#3B82F6", executing: "#10B981", monitoring: "#F59E0B", closing: "#EF4444",
};

interface DocSpace { id: string; projectId: string; projectName: string; docCount: number; autoGeneratedCount: number; createdAt: string; updatedAt: string; }
interface DocItem { id: string; spaceId: string; processGroupKey: string; processKey: string; title: string; content: string; docType: string; reportType: string; status: string; tags: string[]; aiGenerated: number; createdBy: string; createdAt: string; updatedAt: string; }
interface ProcessGroup { key: string; label: string; labelShort: string; icon: string; color: string; description: string; processes: { key: string; label: string; docs: string[] }[]; }
interface ReportTemplate { [key: string]: { label: string; template: string }; }

const ProjectDocSpacePage: React.FC = () => {
  const { message } = App.useApp();
  const [projects, setProjects] = useState<any[]>([]);
  const [projectId, setProjectId] = useState<string>("");
  const [space, setSpace] = useState<DocSpace | null>(null);
  const [docs, setDocs] = useState<DocItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [processGroups, setProcessGroups] = useState<ProcessGroup[]>([]);
  const [reportTemplates, setReportTemplates] = useState<ReportTemplate>({});
  const [stats, setStats] = useState<any>(null);

  // 文档操作
  const [docModalOpen, setDocModalOpen] = useState(false);
  const [docForm] = Form.useForm();
  const [viewDoc, setViewDoc] = useState<DocItem | null>(null);
  const [editDoc, setEditDoc] = useState<DocItem | null>(null);
  const [aiModalOpen, setAiModalOpen] = useState(false);
  const [aiForm] = Form.useForm();
  const [aiGenerating, setAiGenerating] = useState(false);

  // 加载项目列表
  useEffect(() => { projectApi.list().then((r: any) => setProjects(r?.items || r || [])).catch(() => {}); }, []);

  // 加载/初始化文档空间
  const loadSpace = useCallback(async () => {
    if (!projectId) { setSpace(null); setDocs([]); return; }
    setLoading(true);
    try {
      const [sp, pg, rt] = await Promise.all([
        projectDocsApi.getSpaceByProject(projectId),
        projectDocsApi.getProcessGroups(),
        projectDocsApi.getReportTemplates(),
      ]);
      setSpace(sp);
      setProcessGroups(pg || []);
      setReportTemplates(rt || {});

      // 加载文档列表和统计
      if (sp?.id) {
        const [ds, st] = await Promise.all([
          projectDocsApi.listDocuments(sp.id),
          projectDocsApi.getStats(sp.id),
        ]);
        setDocs(ds?.items || []);
        setStats(st);
      }
    } catch (e) { message.error("加载文档空间失败"); }
    finally { setLoading(false); }
  }, [projectId]);

  useEffect(() => { loadSpace(); }, [loadSpace]);

  // 初始化模板
  const initTemplates = async () => {
    if (!space?.id) return;
    try {
      const r: any = await projectDocsApi.initTemplates(space.id);
      message.success(`已初始化 ${r.totalCreated || 0} 个过程模板文档`);
      loadSpace();
    } catch (e) { message.error("初始化失败"); }
  };

  // AI 生成文档
  const handleAIGenerate = async (values: any) => {
    if (!space?.id) return;
    setAiGenerating(true);
    try {
      const r: any = await projectDocsApi.aiGenerate(space.id, values);
      message.success("✅ AI 文档已生成！");
      setAiModalOpen(false);
      aiForm.resetFields();
      loadSpace();
      // 自动打开生成的文档查看
      if (r?.id) {
        const full: any = await projectDocsApi.getDocument(r.id);
        setViewDoc(full);
      }
    } catch (e: any) {
      if (e?.response?.status === 409) {
        antMessage.warning("相同参数的文档已存在，请修改参数后重试");
      } else {
        message.error(e?.response?.data?.detail || "AI 生成失败");
      }
    } finally { setAiGenerating(false); }
  };

  // 创建文档
  const handleCreateDoc = async (values: any) => {
    if (!space?.id) return;
    try {
      await projectDocsApi.createDocument(space.id, values);
      message.success("文档已创建");
      setDocModalOpen(false); docForm.resetFields();
      loadSpace();
    } catch (e) { message.error("创建失败"); }
  };

  // 删除文档
  const handleDeleteDoc = async (id: string) => {
    try { await projectDocsApi.deleteDocument(id); message.success("已删除"); loadSpace(); }
    catch (e) { message.error("删除失败"); }
  };

  // 构建过程组树数据
  const buildTreeData = (): any[] => {
    return (processGroups || []).map((pg) => ({
      key: `pg-${pg.key}`,
      title: (
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ fontSize: 18 }}>{pg.icon}</span>
          <span style={{ fontWeight: 600 }}>{pg.labelShort}</span>
          <Tag color={GROUP_COLORS[pg.key]} style={{ marginLeft: "auto" }}>
            {docs.filter(d => d.processGroupKey === pg.key).length} 篇
          </Tag>
        </div>
      ),
      children: pg.processes.map((proc) => {
        const procDocs = docs.filter(d => d.processKey === proc.key);
        return {
          key: `proc-${proc.key}`,
          isLeaf: true,
          title: (
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%", paddingRight: 8 }}>
              <span>{proc.label}</span>
              <Space size={4}>
                {procDocs.length > 0 && <Badge count={procDocs.length} showZero size="small" />}
                {procDocs.some(d => d.aiGenerated >= 1) && <RobotOutlined style={{ color: "#7C3AED", fontSize: 12 }} />}
              </Space>
            </div>
          ),
          _processKey: proc.key,
          _groupKey: pg.key,
          _docs: procDocs,
        };
      }),
    }));
  };

  // 按过程组过滤的文档
  const filteredDocs = (groupKey?: string, processKey?: string): DocItem[] => {
    let result = docs;
    if (groupKey) result = result.filter(d => d.processGroupKey === groupKey);
    if (processKey) result = result.filter(d => d.processKey === processKey);
    return result;
  };

  // 选择树节点时更新右侧视图
  const [selectedNode, setSelectedNode] = useState<string>("");
  const onTreeSelect = (keys: string[], info: any) => {
    const key = keys[0];
    setSelectedNode(key || "");
    if (info.node?._processKey) {
      // 选中了某个过程，显示该过程的文档
    }
  };

  return (
    <div>
      {/* Header */}
      <div className="page-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
        <div>
          <Title level={4} style={{ margin: 0 }}>
            <DatabaseOutlined /> 项目文档空间
          </Title>
          <Text type="secondary">PMBOK 第 8 版 · 五大过程组 × 40+ 过程 · AI 自动文档生成</Text>
        </div>
        <Space wrap>
          <Select allowClear placeholder="选择项目" style={{ width: 220 }} value={projectId || undefined}
            onChange={(v) => setProjectId(v || "")} showSearch optionFilterProp="label"
            options={projects.map((p: any) => ({ label: p.name, value: p.id }))} />
          {space && (
            <>
              <Button icon={<ReloadOutlined />} onClick={initTemplates}>初始化过程模板</Button>
              <Button type="primary" icon={<RobotOutlined />} onClick={() => setAiModalOpen(true)}>AI 生成文档</Button>
              <Button icon={<PlusOutlined />} onClick={() => setDocModalOpen(true)}>新建文档</Button>
            </>
          )}
        </Space>
      </div>

      {!projectId ? (
        <Card><Empty description="请先选择一个项目以查看其文档空间" /></Card>
      ) : loading ? (
        <Card><Spin size="large" style={{ display: "block", margin: "40px auto" }} /></Card>
      ) : space ? (
        <Row gutter={16}>
          {/* 左侧：过程组树 */}
          <Col xs={24} lg={8}>
            <Card title={<span><BookOutlined /> PMBOK 过程组</span>}
              extra={<Text type="secondary">{space.projectName}</Text>} style={{ borderRadius: 16 }}
              bodyStyle={{ padding: 12, maxHeight: "70vh", overflow: "auto" }}>
              <Tree showLine blockNode defaultExpandAll treeData={buildTreeData()}
                onSelect={onTreeSelect} selectedKeys={[selectedNode]}
                style={{ fontSize: 13 }} />
            </Card>

            {/* 统计卡片 */}
            {stats && (
              <Row gutter={[8, 8]} style={{ marginTop: 12 }}>
                <Col span={12}>
                  <Card size="small"><Statistic title="总文档数" value={stats.totalDocuments || 0} prefix={<FileTextOutlined />} /></Card>
                </Col>
                <Col span={12}>
                  <Card size="small"><Statistic title="AI 生成" value={stats.aiGeneratedCount || 0}
                    prefix={<RobotOutlined />} valueStyle={{ color: "#7C3AED" }}
                    suffix={`/ ${stats.totalDocuments || 0}`} /></Card>
                </Col>
              </Row>
            )}
          </Col>

          {/* 右侧：文档列表 */}
          <Col xs={24} lg={16}>
            <Card title={
              <Space>
                <FileSearchOutlined /> 文档列表
                {selectedNode.includes("proc-") && <Tag color="blue">{selectedNode.replace("proc-", "")}</Tag>}
              </Space>
            }
            extra={<Text type="secondary">{docs.length} 篇文档</Text>} style={{ borderRadius: 16 }}>
              <List
                dataSource={selectedNode.startsWith("proc-")
                  ? filteredDocs(undefined, selectedNode.replace("proc-", ""))
                  : selectedNode.startsWith("pg-")
                    ? filteredDocs(selectedNode.replace("pg-", ""))
                    : docs
                }
                renderItem={(item: DocItem) => (
                  <List.Item actions={[
                    <Button size="small" type="link" icon={<EyeOutlined />} onClick={() => { setViewDoc(item); }}>查看</Button>,
                    <Button size="small" type="link" icon={<EditOutlined />} onClick={() => setEditDoc(item)}>编辑</Button>,
                    <Popconfirm title="确定删除？" onConfirm={() => handleDeleteDoc(item.id)}>
                      <Button size="small" type="link" danger icon={<DeleteOutlined />} />
                    </Popconfirm>,
                  ]}>
                    <List.Item.Meta
                      avatar={
                        <div style={{
                          width: 36, height: 36, borderRadius: 8, background: GROUP_COLORS[item.processGroupKey] || "#E2E8F0",
                          display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, flexShrink: 0,
                        }}>
                          {GROUP_ICONS[item.processGroupKey] || "📄"}
                        </div>
                      }
                      title={
                        <Space>
                          <Text strong>{item.title}</Text>
                          {item.aiGenerated >= 1 && <Tag color="purple" icon={<RobotOutlined />}>AI</Tag>}
                          <Tag style={{ fontSize: 11 }}>{item.status === "approved" ? "已审批" : item.status === "draft" ? "草稿" : item.status}</Tag>
                        </Space>
                      }
                      description={
                        <Space size={4} wrap>
                          {(item.tags || []).slice(0, 3).map((t: string) => <Tag key={t} style={{ fontSize: 10 }}>{t}</Tag>)}
                          <Text type="secondary" style={{ fontSize: 11 }}>{new Date(item.updatedAt).toLocaleDateString()}</Text>
                          <Text type="secondary" style={{ fontSize: 11 }}>{item.createdBy}</Text>
                        </Space>
                      }
                    />
                  </List.Item>
                )}
                locale={{ emptyText: <Empty description="该过程组暂无文档，点击「AI 生成」或「新建文档」" /> }}
              />
            </Card>
          </Col>
        </Row>
      ) : (
        <Card><Empty description="文档空间加载中..." /></Card>
      )}

      {/* 新建文档弹窗 */}
      <Modal title="新建项目文档" open={docModalOpen} onCancel={() => setDocModalOpen(false)} footer={null} width={640} destroyOnClose>
        <Form form={docForm} layout="vertical" onFinish={handleCreateDoc}>
          <Form.Item label="所属过程组" name="process_group_key" rules={[{ required: true }]}>
            <Select options={(processGroups || []).map((pg: any) => ({ label: `${pg.icon} ${pg.labelShort}`, value: pg.key }))} />
          </Form.Item>
          <Form.Item label="所属过程" name="process_key" rules={[{ required: true }]}>
            <Input placeholder="如 charter / wbs / risk_register / integrate_cc 等" />
          </Form.Item>
          <Form.Item label="文档标题" name="title" rules={[{ required: true }]}><Input /></Form.Item>
          <Form.Item label="内容（Markdown）" name="content"><TextArea rows={8} placeholder="输入 Markdown 格式文档内容..." /></Form.Item>
          <Form.Item><Button type="primary" htmlType="submit" block>创建文档</Button></Form.Item>
        </Form>
      </Modal>

      {/* AI 生成弹窗 */}
      <Modal title={<span><RobotOutlined /> AI 智能文档生成</span>} open={aiModalOpen} onCancel={() => setAiModalOpen(false)} footer={null} width={600} destroyOnClose>
        <Alert type="info" showIcon message="基于 PMI 知识体系，自动从项目数据中提取信息并生成专业项目管理文档" style={{ marginBottom: 16 }} />
        <Form form={aiForm} layout="vertical" onFinish={handleAIGenerate}>
          <Form.Item label="报告类型" name="report_type" rules={[{ required: true }]}>
            <Select options={Object.entries(reportTemplates).map(([k, v]: any) => ({ label: v.label, value: k }))} />
          </Form.Item>
          <Row gutter={12}>
            <Col span={12}>
              <Form.Item label="归属过程组" name="process_group_key">
                <Select options={(processGroups || []).map((pg: any) => ({ label: pg.labelShort, value: pg.key }))} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="归属过程" name="process_key">
                <Input placeholder="可选" />
              </Form.Item>
            </Col>
          </Row>
          <Form.Item label="补充说明（可选）" name="custom_prompt">
            <TextArea rows={3} placeholder="例如：重点关注进度偏差、突出风险应对措施..." />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" icon={<RobotOutlined />} loading={aiGenerating} block>
              {aiGenerating ? "AI 正在生成中..." : "开始生成"}
            </Button>
          </Form.Item>
        </Form>
      </Modal>

      {/* 查看文档 Drawer */}
      {viewDoc && (
        <Modal title={viewDoc.title} open={!!viewDoc} onCancel={() => setViewDoc(null)} footer={null} width={800}
          extra={
            <Space>
              {viewDoc.tags?.map((t: string) => <Tag key={t}>{t}</Tag>)}
              {viewDoc.aiGenerated >= 1 && <Tag color="purple" icon={<RobotOutlined />}>AI 生成</Tag>}
            </Space>
          }>
          <Descriptions column={2} size="small" bordered style={{ marginBottom: 16 }}>
            <Descriptions.Item label="过程组">{(processGroups.find(pg => pg.key === viewDoc.processGroupKey))?.labelShort || viewDoc.processGroupKey}</Descriptions.Item>
            <Descriptions.Item label="状态"><Tag>{viewDoc.status}</Tag></Descriptions.Item>
            <Descriptions.Item label="类型">{viewDoc.docType === "ai_generated" ? "AI 生成" : viewDoc.docType === "template" ? "模板" : "手工"}</Descriptions.Item>
            <Descriptions.Item label="版本">v{viewDoc.version || 1}</Descriptions.Item>
            <Descriptions.Item label="创建者">{viewDoc.createdBy}</Descriptions.Item>
            <Descriptions.Item label="更新时间">{new Date(viewDoc.updatedAt).toLocaleString()}</Descriptions.Item>
          </Descriptions>
          <Divider />
          <div style={{ background: "#FAFAFA", borderRadius: 12, padding: 20, border: "1px solid #E2E8F0" }}>
            <pre style={{ whiteSpace: "pre-wrap", fontFamily: "'Inter', system-ui", lineHeight: 1.8, fontSize: 14, margin: 0, maxHeight: "50vh", overflow: "auto" }}>
              {viewDoc.content || "(空内容)"}
            </pre>
          </div>
        </Modal>
      )}
    </div>
  );
};

export default ProjectDocSpacePage;
